# SPDX-FileCopyrightText: 2024 ash_mysql contributors <https://github.com/ash-project/ash_mysql/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshMysql.ActionSelectTest do
  @moduledoc false
  use AshMysql.RepoCase, async: false
  alias AshMysql.Test.{IntegerPost, Post}

  require Ash.Query

  defp capture_queries(fun) do
    ref = make_ref()
    parent = self()
    handler_id = {__MODULE__, ref}

    :telemetry.attach(
      handler_id,
      [:ash_mysql, :test_repo, :query],
      fn _event, _measurements, metadata, _config ->
        send(parent, {ref, metadata.query})
      end,
      nil
    )

    try do
      result = fun.()
      {result, drain_queries(ref)}
    after
      :telemetry.detach(handler_id)
    end
  end

  defp drain_queries(ref, acc \\ []) do
    receive do
      {^ref, query} -> drain_queries(ref, [query | acc])
    after
      0 -> Enum.reverse(acc)
    end
  end

  # Only the SELECT list — assertions on pkey columns must not accidentally
  # match the WHERE clause (`WHERE s0.[id] IN ...`).
  defp select_clause(query) do
    query |> String.split(" FROM ") |> hd()
  end

  defp insert_reload_query(queries) do
    # The reload SELECT issued by the data layer runs inside the insert
    # transaction, i.e. before the commit. Queries after the commit come from
    # ash core (e.g. `process_results` re-loading fields), not from the data
    # layer.
    queries
    |> Enum.take_while(&(&1 != "commit"))
    |> Enum.find(fn query ->
      String.starts_with?(query, "SELECT") and String.contains?(query, "posts")
    end)
  end

  test "bulk create with a select only reloads the selected fields" do
    {result, queries} =
      capture_queries(fn ->
        Ash.bulk_create!(
          [%{title: "fred", score: 3}, %{title: "george", score: 4}],
          Post,
          :create_barebones,
          return_records?: true,
          select: [:title]
        )
      end)

    assert [%{title: "fred"}, %{title: "george"}] =
             Enum.sort_by(result.records, & &1.title)

    reload_query = insert_reload_query(queries)

    assert reload_query, "expected a reload SELECT against posts, got: #{inspect(queries)}"
    assert select_clause(reload_query) =~ "[id]"
    assert select_clause(reload_query) =~ "[title]"
    refute reload_query =~ "[score]"
    refute reload_query =~ "[stuff]"
  end

  test "bulk create without a select reloads the default-selected fields and returns full records" do
    {result, queries} =
      capture_queries(fn ->
        Ash.bulk_create!([%{title: "fred", score: 3}], Post, :create_barebones,
          return_records?: true
        )
      end)

    assert [%{title: "fred", score: 3}] = result.records

    # No explicit select means all default-selected attributes are reloaded,
    # so ash core has no reason to issue a second SELECT after the commit.
    reload_query = insert_reload_query(queries)
    assert reload_query =~ "[score]"

    assert "commit" in queries

    refute Enum.any?(
             Enum.drop_while(queries, &(&1 != "commit")),
             &String.starts_with?(&1, "SELECT")
           )
  end

  test "creates with database-generated integer primary keys still reload real values" do
    # Integer pkeys are generated by the database, so the reload cannot use a
    # `WHERE id IN` on client-known keys and goes through the SCOPE_IDENTITY()
    # branch (or its fallback) with the trimmed select applied.
    post =
      IntegerPost
      |> Ash.Changeset.for_create(:create, %{title: "fred"})
      |> Ash.create!()

    assert %{title: "fred"} = post
    assert is_integer(post.id)
  end

  test "single create with a changeset select only reloads the selected fields" do
    {post, queries} =
      capture_queries(fn ->
        Post
        |> Ash.Changeset.for_create(:create_barebones, %{title: "fred", score: 5})
        |> Ash.Changeset.select([:title])
        |> Ash.create!()
      end)

    assert %{title: "fred", score: %Ash.NotLoaded{}} = post

    reload_query = insert_reload_query(queries)

    assert reload_query, "expected a reload SELECT against posts, got: #{inspect(queries)}"
    assert reload_query =~ "[title]"
    refute reload_query =~ "[score]"
  end

  test "non-default-selected attributes are not reloaded, but always_select? ones are" do
    {post, queries} =
      capture_queries(fn ->
        Post
        |> Ash.Changeset.for_create(:create_barebones, %{
          title: "fred",
          uniq_custom_one: "not selected by default",
          uniq_custom_two: "always selected"
        })
        |> Ash.create!()
      end)

    # uniq_custom_one is select_by_default?: false and wasn't requested, so it
    # must come back as NotLoaded — not as a loaded nil.
    assert %Ash.NotLoaded{} = post.uniq_custom_one

    # uniq_custom_two is always_select?: true. Ash core's NotLoaded masking
    # assumes the data layer loaded it, so the data layer must reload it even
    # though it isn't selected by default.
    assert post.uniq_custom_two == "always selected"

    reload_query = insert_reload_query(queries)
    refute reload_query =~ "[uniq_custom_one]"
    assert reload_query =~ "[uniq_custom_two]"
  end

  test "updates reload fields the changeset data doesn't carry" do
    _post =
      Post
      |> Ash.Changeset.for_create(:create_barebones, %{
        title: "fred",
        uniq_custom_two: "always selected"
      })
      |> Ash.create!()

    # Fetch a copy where everything but the pkey is NotLoaded, then update it.
    # The data layer must reload whatever the changeset can't provide itself:
    # regular action_select fields (title) and always_select? attributes
    # (uniq_custom_two) alike.
    [narrow] = Ash.read!(Ash.Query.select(Post, [:id]))

    updated =
      narrow
      |> Ash.Changeset.for_update(:update, %{score: 7})
      |> Ash.update!()

    assert updated.score == 7
    assert updated.title == "fred"
    assert updated.uniq_custom_two == "always selected"
  end

  test "update with a changeset select trims the reload query" do
    post =
      Post
      |> Ash.Changeset.for_create(:create_barebones, %{title: "fred"})
      |> Ash.create!()

    {updated, queries} =
      capture_queries(fn ->
        post
        |> Ash.Changeset.for_update(:update, %{score: 9})
        |> Ash.Changeset.select([:title])
        |> Ash.update!()
      end)

    # score was written but not selected, so ash core masks it.
    assert %Ash.NotLoaded{} = updated.score
    assert updated.title == "fred"

    reload_query = insert_reload_query(queries)

    assert reload_query, "expected a reload SELECT against posts, got: #{inspect(queries)}"
    assert select_clause(reload_query) =~ "[title]"
    refute reload_query =~ "[stuff]"
    refute reload_query =~ "[category]"
  end

  test "single create through an action with changes still returns full records" do
    post =
      Post
      |> Ash.Changeset.for_create(:create, %{title: "fred", score: 5})
      |> Ash.create!()

    assert %{title: "fred", score: 5} = post
  end

  test "updates still return correct values with action_select in play" do
    post =
      Post
      |> Ash.Changeset.for_create(:create, %{title: "fred", score: 1})
      |> Ash.create!()

    updated =
      post
      |> Ash.Changeset.for_update(:update, %{score: 2})
      |> Ash.update!()

    assert %{title: "fred", score: 2} = updated
  end

  test "atomic updates still reload atomic values" do
    post =
      Post
      |> Ash.Changeset.for_create(:create, %{title: "fred", score: 1})
      |> Ash.create!()

    assert %{score: 3} = Post.increment_score!(post, 2)
  end
end
