defmodule AshMysql.TestRepo.Migrations.CiStringMssqlCollation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_mysql.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify :category, :"NVARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AI"
    end
  end

  def down do
    alter table(:posts) do
      modify :category, :"VARCHAR(255)"
    end
  end
end