defmodule AshMysql.TestRepo.Migrations.AddPostEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_mysql.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :email, :string
    end
  end

  def down do
    alter table(:posts) do
      remove :email
    end
  end
end